language: rust
sudo: required
cache: cargo
rust:
  - nightly
git:
  depth: 5
branches:
  only:
  - master
notifications:
  email:
    on_success: change
    on_failure: change

services:
  - postgresql
before_script:
  - mv .travis.env .env
  - source .env
  - cargo install diesel_cli
  - psql -c 'create database travis_ci_test;' -U postgres
  - diesel migration run
