[package]
name = "pupil-server"
version = "0.1.0"
authors = ["cgm616 <cgm616@me.com>"]

[dependencies]
time = "0.1.36"
rocket = "0.2.0"
rocket_codegen = "0.2.0"
jsonwebtoken = { git = "https://github.com/Keats/rust-jwt" }
rustc-serialize = "0.3"
diesel = "0.9.0"
diesel_codegen = { version = "0.9.0", features = ["postgres"] }
dotenv = "0.8.0"
rand = "0.3"
argon2rs = "0.2.5"

[dependencies.rocket_contrib]
version = "0.1.6"
default-features = false
features = ["handlebars_templates"]
