[package]
name = "pupil-server"
version = "0.1.0"
authors = ["cgm616 <cgm616@me.com>"]

[dependencies]
time = "0.1.36"
rocket = "0.1.6"
rocket_codegen = "0.1.6"
jsonwebtoken = { git = "https://github.com/Keats/rust-jwt" }
rustc-serialize = "0.3"

[dependencies.rocket_contrib]
version = "0.1.6"
default-features = false
features = ["handlebars_templates"]
